### PR TITLE
Create and Update Temperature Sensor on Domoticz

### PR DESCRIPTION
**Pull request by NoelieRamuzat**
Todo : Create 2 files : one for creating and one for Updating

### CODE REVIEW

**Comment by pblottiere** [comment]
Hi Noelie!

Thank you your work on this PR!

I just merged another PR so you have to rebase with master and resolve some conflicts. To do that:

``` shell
$ git remote add upstream https://github.com/pblottiere/dominus
$ git checkout master
$ git fetch upstream master
$ git merge upstream/master
$ git checkout dominus
$ git rebase master # and resolve conflict 
```

Moreover, can you move `domoticz_create_assign.cpp` in `src/domoticz` and update the corresponding README please?

Let me know if you don't have time, I'll do it myself. Otherwise, good luck!

**Comment by NoelieRamuzat** [comment]
Hi M. Blottière,

I actually do not know how to deal with the two languages (C / C++) in this project. Indeed, creating two configure.ac (e.g. configure_cpp.ac & configure_c.ac) would not work since ./configure search for a file named "configure.ac". Would it be possible to create a Makefile which is able to compile both languages ?

Thank you for your time.

Noelie Ramuzat

**Comment by pblottiere** [comment]
Hi @NoelieRamuzat!

> Hi M. Blottière

You can just use '@pblottiere' instead of `M. Blottière`, especially on github :).

> Would it be possible to create a Makefile which is able to compile both languages ?

I created a branch `configure_cpp` where I added a `hello.cpp` file. You can take a look to this commit https://github.com/pblottiere/dominus/commit/ecca64696c63179e3dfca18fa62944e68f30fec3. I think it will help you in your work.

And sorry for the delay!

**Comment by NoelieRamuzat** [comment]
Hi @pblottiere,

I have created a new pull request instead of this one which was not well implemented (on master instead of a branch, which was not following your repository).
The new request is the following : https://github.com/pblottiere/dominus/pull/9 

Noëlie RAMUZAT

**Pull request closed without merging**
