### PR TITLE
Created the Dockerfile

### PR DESCRIPTION
**Pull request by TilletJ**
Dockerfile couldn't be tested due to the instable wifi connexion in ENSTA Bretagne.

### CODE REVIEW

**Comment by pblottiere** [comment]
Firstly, thank you for this PR :+1:!

But I have some issues when I want to build the image from the Dockerfile:

``` shell
 ---> Running in f8c21335c6c1
--2017-12-05 19:14:52--  https://github.com/TilletJ/dominus/tree/dockerfile/.config
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/TilletJ/dominus/blob/dockerfile/.config [following]
--2017-12-05 19:14:53--  https://github.com/TilletJ/dominus/blob/dockerfile/.config
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '.config.1'

     0K .......... .......... .......... .......... ..........  216K
    50K .......... .......... .......... .......... ..........  487K
   100K .......... .......... .......... .......... ..........  882K
   150K .......... .......... .......... .......... ..........  878K
   200K .......... .......... .......... .......... ..........  878K
   250K .......... .......... .......... .......... ..........  775K
   300K .......... .......... .......... .......... ..........  957K
   350K .......... .......... .......... .......... .......... 1000K
   400K .......... .......... .......... .......... ..........  212K
   450K .......... .......... .......... .......... .......... 5.22M
   500K .......... .......... .......... .......... ..........  170M
   550K .......... .......... .......... .......... ..........  528M
   600K .......... .........                                    173M=0.9s

2017-12-05 19:14:54 (675 KB/s) - '.config.1' saved [634122]

 ---> 6c707b122f0b
Removing intermediate container f8c21335c6c1
Step 9/10 : RUN make
 ---> Running in aa5337da401b
/usr/bin/make -j1 O=/root/buildroot-2017.08/output HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
make[1]: Entering directory '/root/buildroot-2017.08'
make[1]: Leaving directory '/root/buildroot-2017.08'
You must install 'unzip' on your build machine
support/dependencies/dependencies.mk:22: recipe for target 'core-dependencies' failed
make: *** [core-dependencies] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
blottiere@zalman:dominus [dockerfile] $ docker build .
```

Moreover, did you update the Dockerfile with sqlite for lua and increase the corresponding size (cf some issues happened during practical work)?

Let me know if you don't have time and I'll fix this myself.

Thank you again!

**Comment by TilletJ** [comment]
Now the image building from the Dockerfile works well.
I added a README file to explain how build the image and what it contains.

**Comment by pblottiere** [comment]
Nice, thank you for updating this PR!

Just a note about this part in the `Dockerfile`:

``` shell
RUN wget https://github.com/TilletJ/dominus/tree/dockerfile/users.tables
```
Firstly, I don't think it's working because `users.tables` does not exist on your branch :). Moreover, you should use this Docker syntax instead when you want to copy a file from the host machine to a container:

``` shell
COPY users.tables /root/buildroot-2017.08/users.tables
```

Once fixed, I'll merge your PR without hesitation then ;).

**Comment by pblottiere** [comment]
Ah and I just merged another PR. So you have to rebase your branch and resolve some conflicts:

``` shell
$ git remote add upstream  https://github.com/pblottiere/dominus
$ git checkout master
$ git fetch upstream master
$ git merge upstream/master
$ git checkout dockerfile
$ git rebase master
```

Let me know.

**Comment by TilletJ** [comment]
I replaced the 'RUN wget' commands with 'COPY', and I successfully rebased my branch with the other PR. I also enjoyed the rebase command to rename and squash some of my commits, to try to have a cleaner work flow.

**Comment by pblottiere** [comment]
Thank you @TilletJ!

**Pull request merged**
